### ISSUE TITLE
Hmm... mast?!

### ISSUE THREAD

**Issue by alexezeder** [InfinityQX70s/private-disk#1]
Change word _m_**_a**__st_ to _m_**_u**__st_ in overview, please. Of course if you don't mean mast on ship.

**Comment by mmazurkevich** [comment]
Ok, thank you for remark. I will do this in the near future

**Comment by alexezeder** [comment]
Also, Apach →Apach**e**

**Comment by alexezeder** [comment]
why did you even reopen this?
